create database prueba;
use prueba;
create table GENDERS(  
  ID_GENDERS INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL);


create table JOBS(  
  ID_JOB INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  salary DOUBLE NOT NULL);

create table EMPLOYEES(  
  ID_EMPLOYEES INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  GENDER_ID INT not null,
  JOB_ID INT not null,
  FOREIGN KEY(GENDER_ID) REFERENCES GENDERS(ID_GENDERS),
  FOREIGN KEY(JOB_ID) REFERENCES JOBS(ID_JOB),
  NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  BIRTHDATE DATE
);
create table EMPLOYEE_WORKED_HOURS(  
  Id_WORKED_HOURS INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EMPLOYEE_ID INT not null ,
  FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(ID_EMPLOYEES),
  WORKED_HOURS INT NOT NULL,
  WORKED_DATE DATE);

INSERT INTO `prueba`.`GENDERS` (`name`) VALUES ('Hombre');
INSERT INTO `prueba`.`JOBS` (`name`, `salary`) VALUES ('dev', '300');

